name: wilma
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  adaptive_dialog: ^1.8.2
  faker: ^2.0.0
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  getwidget: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_ui: ^1.0.13
  image_picker_for_web: ^2.1.12
  image_picker: ^0.8.7
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  image_network: ^2.5.1
  scaffold_gradient_background: ^1.0.3+1
  flutter_spinbox: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:

    - images/
    - images/icons/
    - images/logos/
    - images/vehicules/
    - images/serv/
